NumPy Program Practice Questions

- Write a NumPy program to create an array of 10 zeros.
- Write a NumPy program to create an array of 10 ones.
- Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.
- Write a NumPy program to reverse an array (first element becomes the last).
- Write a NumPy program to extract all odd numbers from an array.
- Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.
- Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.
- Write a NumPy program to create a 2D array with 1 on the border and 0 inside.
- Write a NumPy program to multiply two given matrices.
- Write a NumPy program to find the unique elements of an array.
- Write a NumPy program to extract the elements in the odd-numbered columns of a 2D array.
- Write a NumPy program to extract the elements in the even-numbered rows of a 2D array.
- Write a NumPy program to extract a subarray from a given array. The subarray should include the first 3 rows and the columns from index - 1 to 4 (inclusive).
- Write a NumPy program to reverse the order of elements in each column of a 2D array.
- Write a NumPy program to create a diagonal matrix from a given 1D array. The elements below the diagonal should be zero, and the elements above the diagonal should be squared.

In [4]:
# Write a NumPy program to create an array of 10 zeros
import  numpy as np
zeros_arr = np.zeros([10])
print(zeros_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# Write a NumPy program to create an array of 10 ones
ones_arr = np.ones([10])
print(ones_arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
#Write a NumPy program to reverse an array (first element becomes the last).
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[::-1])
print(type(arr))

[9 8 7 6 5 4 3 2 1]
<class 'numpy.ndarray'>


In [18]:
#Write a NumPy program to extract all odd numbers from an array.
arr = np.array([1,2,3,4,5,6,7,8,9,10])

odd_numbers = arr[arr%2 == 1]
print(odd_numbers)

[1 3 5 7 9]


In [19]:
#Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

sum_of_elements = np.sum(arr)   #computing sum
mean_of_elements = np.mean(arr) #computing mean
std_deviation = np.std(arr)     #computing standard deviation

print("Sum:", sum_of_elements)
print("Mean:", mean_of_elements)
print("Standard Deviation:", std_deviation)


Sum: 150
Mean: 30.0
Standard Deviation: 14.142135623730951


In [24]:
#Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.
random_arr = np.random.rand(5, 5)
print(random_arr)

print(np.max(random_arr) , np.mean(random_arr))

[[0.91890813 0.5587866  0.81161071 0.31184384 0.83173494]
 [0.06672743 0.60264126 0.67803628 0.91346331 0.62826934]
 [0.56584945 0.06004848 0.67341346 0.16790475 0.31632844]
 [0.83571747 0.90527378 0.0495519  0.68239545 0.48173699]
 [0.60020821 0.5029774  0.4190398  0.02508997 0.36045387]]
0.9189081288490951 0.5187204500892068


In [25]:
#Write a NumPy program to create a 2D array with 1 on the border and 0 inside.
import numpy as np
rows, cols = 5, 5

matrix = np.zeros((rows, cols), dtype=int)
matrix[0, :] = 1  
matrix[-1, :] = 1  
matrix[:, 0] = 1  
matrix[:, -1] = 1  

print(matrix)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [28]:
# Write a NumPy program to multiply two given matrices.
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])

array = ar1.dot(ar2)
arr_1 = ar1 @ ar2
print(array)
print(arr_1)

32
32


In [29]:
#Write a NumPy program to find the unique elements of an array.
import numpy as np

arr = np.array([1, 2, 3, 4, 2, 4, 5, 3, 5, 6, 5, 7])

unique_elements = np.unique(arr)
print("Unique elements:", unique_elements)

Unique elements: [1 2 3 4 5 6 7]


In [30]:
import numpy as np
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

odd_columns = matrix[:, ::2]
print("Original Matrix:\n", matrix)
print("Extracted Odd-Numbered Columns:\n", odd_columns)


Original Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Extracted Odd-Numbered Columns:
 [[ 1  3]
 [ 5  7]
 [ 9 11]]


In [37]:
#Write a NumPy program to extract the elements in the even-numbered rows of a 2D array.
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13,14,15,16]
])

even_columns = matrix[1::2, :]
print("Original Matrix:\n", matrix)
print("Extracted Even-Numbered Columns:\n", even_columns)

Original Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Extracted Even-Numbered Columns:
 [[ 5  6  7  8]
 [13 14 15 16]]


In [39]:
#Write a NumPy program to extract a subarray from a given array. The subarray should include the first 3 rows 
#and the columns from index - 1 to 4 (inclusive).
import numpy as np
matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

subarray = matrix[:3, 1:5]  
print("Original Matrix:\n", matrix)
print("Extracted Subarray:\n", subarray)

Original Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Extracted Subarray:
 [[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]


In [40]:
#Write a NumPy program to reverse the order of elements in each column of a 2D array.
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
reversed_columns = matrix[::-1, :]
print("Original Matrix:\n", matrix)
print("Matrix with Reversed Columns:\n", reversed_columns)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix with Reversed Columns:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [41]:
#Write a NumPy program to create a diagonal matrix from a given 1D array.The elements below the diagonal should be zero, 
#and the elements above the diagonal should be squared.
import numpy as np
arr = np.array([1, 2, 3, 4])

n = len(arr)
matrix = np.zeros((n, n), dtype=int)

np.fill_diagonal(matrix, arr)

for i in range(n):
    for j in range(i + 1, n):  
        matrix[i, j] = arr[j] ** 2

print("Diagonal Matrix with Squared Upper Triangle:\n", matrix)


Diagonal Matrix with Squared Upper Triangle:
 [[ 1  4  9 16]
 [ 0  2  9 16]
 [ 0  0  3 16]
 [ 0  0  0  4]]
